### PR TITLE
Wenqing Zhong HW2

### PR DESCRIPTION
**Pull request by WenqingZhong**

### CODE REVIEW

**Comment by zqvqk** [comment]
good.

**Review by yihongliu0121 — COMMENTED** [review]
Love your explanation of the differences between abstract class and interface, very detailed and concise, and you mentioned before and after java8. There is a huge change that interface can have concrete methods starting with Java8

**Comment by yuants4213** [comment]
The information is thorough, and the arrangement is easily understandable.

**Comment by ChovyDavid** [comment]
Well done! Absolutely fantastic work on your assignment! Your attention to detail and thoroughness are truly commendable.

**Comment by kzhou025** [comment]
Great OOP pattern design

**Comment by Tangkaiyuan0311** [comment]
good job

**Comment by yzeng059** [comment]
good job

**Comment by Liam-Zhou** [comment]
very good

**Pull request merged**
