### PR TITLE
Wenqing zhong/hw1

### PR DESCRIPTION
**Pull request by WenqingZhong**
Wenqing Zhong hw1

### CODE REVIEW

**Comment by yzeng059** [comment]
Great job on completing your assignment! Everything appears to be in excellent shape. Congratulations on your hard work!

**Comment by oliverXS** [comment]
Great work on this! I appreciate your effort.

**Comment by Liam-Zhou** [comment]
dont merge to main

**Comment by y1zhuo** [comment]
Good job on hw1!

**Pull request closed without merging**
