### PR TITLE
hw2 done

### PR DESCRIPTION
**Pull request by yihongliu0121**
HW2 Done

### CODE REVIEW

**Comment by ZhouXie-Ryan** [comment]
Good work!

**Comment by Frank-Z-Chen** [comment]
LGTM

**Comment by yuants4213** [comment]
The information is thorough, and the arrangement is easily understandable.

**Comment by stonehard0208** [comment]
very good

**Comment by yzeng059** [comment]
The best parking lot design I've ever seen. Congrats for the great work, gj Yihong!

**Pull request merged**
